var AppView = Backbone.View.extend({

	el: '#app',

	/*
	 *	These views are initialised only once the data has been loaded to the dataStore.
	 *	This uses jQuery Promises
	 */

	preload: {
		queue: require('../../queue/views/view-queue'),
		playlist: require('../../playlists/views/view-playlists')

	},

	/*
	 *	These views can be loaded on start up as they don't rely on external data.
	 */
	
	views: {
		search: require('../../search/views/view-search'),
		tracks: require('../../tracks/views/view-tracks')

	},

	initialize: function(){
		var self = this;

		console.log('App Initialised');

		console.log('Creating global events...');

		/*
		 *	Assign events to the global dispatcher	
		 */

		dispatcher.on('collections-when-pre-loaded', self._startApp.bind(self));
		dispatcher.on('add-track-to-queue', self._addTrackToQueue);
		dispatcher.on('add-track-to-playlist', self._addTrackToPlaylist);
		dispatcher.on('queue-track-vote', self._voteTrack);

		dispatcher.on('tracks-collection-reset', self._addToTracks);

		

		console.log('booting views...');
		
		/*
		 *	Callback for when the deferred object is resolved
		 */

        var loadQueue = self._preloadData();

		$.when(loadQueue).then(function(){
			dispatcher.trigger('collections-when-pre-loaded');
		});

		/*
		 *	Initialise views that don't rely on external data
		 */

		for(var view in self.views){
			new self.views[view]();
		}

	},

	_preloadData: function(){

		/*
		 *	Deferred object to be resolved once data for Playlists and Queue has been loaded
		 */

		var deferred = $.Deferred();

		$.when(
			dataStore.playlistsCollection.fetch(),
			dataStore.queueCollection.fetch()
		).then(function(){
			return deferred.resolve();
		});

		return deferred;
	},

	_startApp: function(){
		// TODO - Remove a preloader

		for(var view in this.preload){
			new this.preload[view]();
		}
	},

	/*
	 *	Functions to be called when events are triggered from the modules.
	 */

	_addToTracks: function(id){

		/*
		 *	
		 */

		// TODO - Fix url
		dataStore.tracksCollection.fetch({
			url: 'http://localhost:8000/api/playlists/' + id,
			add: true,
			remove: true,
		});
	},

	_addTrackToQueue: function(data){

		/*
		 *	Adds the selected track to the queue. This uses the href of the link which is generated on the backend
		 *	and added to the template on render
		 */

		$.ajax({
			method: 'GET',
			url: data.href,
			success: this._addTrackToQueueSuccess,
			error: this._onError
		});
	},

	_addTrackToQueueSuccess: function(res){

		/*
		 *	Callback for a successful call to add track to queue
		 */

		return console.log('add track to queue success', res);
	},

	_addTrackToPlaylist: function(data){

		/*
		 *	Adds the selected track to the playlist. the data is generated by a function in modules/tracks/views/view-track.js
		 */

		// TODO - Fix url, grab url from collection?

		var self = this;

		$.ajax({
			method: 'GET',
			url: 'http://localhost:8000/api/metadata/tracks/add/playlist/?source_type=' + data.sourceType + '&source_id=' + data.sourceId + '&playlist_id=' + data.playlistId,
			success: self._addTrackToPlaylistSuccess,
			error: self._onError
		});
	},

	_addTrackToPlaylistSuccess: function(res){

		/*
		 *	Callback for a successful call to add track to playlist
		 */

		// TODO

		return console.log('Add to playlist success', res);
	},

	_voteTrack: function(data){

		/*
		 *	
		 */

		// TODO

		return console.log(data);
	},

	_onError: function(error){

		/*
		 *	Error callback when an ajax request fails.
		 */

		return console.log('Error', error);
	}
});

module.exports = AppView;